apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: ghcr.io/gurjotkaur20/hello-world:b71c633b977807af30057b2a47ff52ec6ba9f92e
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: OTEL_ENABLED
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: "hello-world"
            - name: OTEL_SERVICE_NAMESPACE
              value: "hellons"              
            - name: SERVER_URL
              value: "http://app.vapd.online:30237"                            